"""Compile the decision report from reviewed records; interpretation remains explicit."""
import json,collections
from urllib.parse import urlparse
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
p=json.loads((ROOT/'products.json').read_text()); by={x['id']:x for x in p}; ranked=sorted(p,key=lambda x:x['rank'])
short=[x for x in ranked if x['decision']=='Validate'][:10]
counts=collections.Counter(x['decision'] for x in p)
checks=json.loads((ROOT/'artifacts'/'catalog-checks.json').read_text())
selected={
'S094':('Finance teams pay to resolve invoice disputes, assign the missing action and reconcile settlement.', 'Payment reminders are already bundled elsewhere. The distinct record must connect the unpaid invoice to the actual disputed deliverable, agreed action and accepted settlement.', 'During discovery, separate three buyer groups: firms with frequent disputed service invoices, firms with late-but-undisputed invoices, and firms wanting outsourced collection labor. Only the first tests this proposition.'),
'S052':('Migration consultancies pay to reduce unpaid rework and obtain clear client acceptance.', 'A complete engagement joins source inventory, mapping revisions, exceptions, dry-run control totals and cutover acceptance. A spreadsheet importer alone does not own this business process.', 'Test consultancies that repeatedly deliver migrations, not companies performing one migration. Require a customer data owner to approve real reconciliations and a second engagement to reuse the record.'),
'S080':('Operations teams pay to connect approved policies to recurring control work and evidence.', 'The core is policy version → assigned control run → exception → review → evidence export. Certification badges or a document wiki alone do not satisfy the proposition.', 'Require customers to show recurring work that stays unowned or cannot be tied to a policy version in their current tools. Human reviewers retain framework interpretation.'),
'S090':('Bid teams pay to complete concurrent proposals with approved, current evidence.', 'Own qualification, requirement responsibility, controlled answer reuse, exception review and submission readiness. AI text generation is an optional capability, not the business.', 'Replay an actual redacted bid in the current tool and the proposed workflow. Measure late expert responses, outdated answers and assembly rework; do not promise win-rate improvements from a tiny pilot.'),
'S055':('Software agencies pay to turn client testing into version-bound release acceptance.', 'Agree business scenarios, collect guest results, track defects and retests, and preserve the final release decision. A bug-report form alone fails the SaaS scope test.', 'Buyers must release to external clients repeatedly and obtain a second-cycle payment. Treat this as an alternative entry to the delivery family, not an automatic second app beside migration delivery.'),
'S039':('Multi-newsletter publishers pay to reconcile sponsor packages, delivery exceptions and billing.', 'Own the sponsor campaign record across reserved placements, approved creative, proof, make-goods and the billing adjustment. Selling advertisers is explicitly outside the product.', 'Start with publishers already closing direct sponsor deals across several publications. If standard Letterhead or Passionfroot configuration handles the real exceptions, reject the idea.'),
'S040':('Content agencies pay to control editorial revisions, contributor cost and client acceptance.', 'The commission joins brief version, contributor commitment, review rounds, approved scope, delivery acceptance and margin. This is an operating product only if those decisions change economics.', 'Replay one profitable and one overrun commission. Identify exactly which approval or scope change caused extra cost; a prettier board is not a paid advantage.'),
'S029':('Course publishers pay to reconcile corporate licenses and renewals across learning systems.', 'Own the corporate agreement, seat allocation, entitlement changes, completion evidence and renewal. The course player remains in the customer LMS.', 'This depends on a narrower segment than all course creators: established publishers with multiple actual systems and employer contracts. Five single-LMS customers cannot validate it.'),
'S009':('Localization agencies pay to reconcile job versions, supplier rates, review acceptance and payables.', 'Own the localization order through language-pair allocation, approved counts/rates, review and delivery. Translation generation and a new translator marketplace are unnecessary.', 'Use actual CAT analysis files and a rate-change exception. Protemos, Plunet and XTM are direct comparisons; neutrality across tools must save work instead of adding another import.'),
'S013':('Remote back-office providers pay to connect accepted work units and rework to billing.', 'A service order governs inputs, processing, quality review, exceptions, accepted-unit counts and closeout. The customer supplies the workers and processing systems.', 'Choose one unit model such as catalog-data maintenance. Require three providers to use the same basic exception and acceptance model without a bespoke execution engine.')}
def distinct_vendors(sources):
 seen=set();out=[]
 for c in sources:
  host=urlparse(c['url']).hostname.removeprefix('www.')
  if host not in seen:seen.add(host);out.append(c)
 return out[:2]
L=[]
def add(s=''):L.append(s)
add('# Fresh analysis of 100 SaaS products')
add();add('Research date: 2026-10-05. Decision: which complete software business should receive customer validation before further implementation?')
add();add('## Recommendation')
add();add('Validate **S052 — Migration delivery workspace** first under an engineering-led founder assumption. Compare **S094 — B2B receivables and dispute operations** as a second, commercially different path. Both can plausibly support a $149/month workspace hypothesis; neither has demonstrated demand for our version. Keep a third product slot uncommitted until buyer access and paid repeated use are known.')
add();add('Migration delivery combines a coherent client-facing operating record with bounded hosting and repeat consultancy customers. It ranks first under both acquisition-heavy and implementation-heavy scoring. Receivables has the highest base-weighted final score because an identifiable finance owner repeatedly deals with unpaid invoices; its main uncertainty is whether buyers want software or collection labor. The founder’s access to either buyer group is unverified, so actual access can reverse the order.')
add();add(f'The completed desk-research funnel is **100 candidate products → 100 independent challenges → {counts["Validate"]} discovery candidates → 10 focused finalists**. The remaining {counts["Reserve"]} are Reserve and {counts["Defer"]} are Defer. These statuses are decisions under the stated constraints, not success probabilities. No interviews, outreach, paid pilots, demand tests or new implementations were performed.')
add();add('## Read the work')
add();add('- [All 100 products, ranked](ranked-100.md): comparison with prices, account targets, cost envelopes and alternative ranks.\n- [All 100 detailed dossiers](catalog-100.md): buyer, value, full workflow, competition, distribution, risks, pricing, MVP and kill gate.\n- [Official evidence register](evidence-register.md): links and observed price qualifications.\n- [Research protocol](research-protocol.md): weights, evidence rules and financial definitions.\n- [Structured dataset](products.json): all records and review history.\n- [Review and scope audit](review-log.md): removed overlaps, limitations and unproven boundaries.')
add();add('## What changed from the earlier micro-SaaS approach')
add();add('Existing prototypes received no bonus. The unit is an ongoing business process with a persistent record, connected stages, multiple roles and a recurring budget owner. A narrow first release remains sensible, but it must complete a valuable cycle. A checker, standalone generator, reminder or dashboard does not qualify merely because additional screens can be imagined.')
add();add('The pool deliberately emphasizes B2B and professional organizations because the objective is $5,000 MRR with a small number of products and modest cash spending. It covers service businesses; education and digital publishing; technical/data operations; and finance, customer operations and governance. It is not an exhaustive search of consumer, gaming, collector or social opportunities. Five duplicate or overly similar entries were replaced during review. Adjacent products still share channels and infrastructure; 100 hypotheses are not 100 independent bets.')
add();add('## Ten finalists for validation')
add();add('Ordered by final score among candidates that passed the qualitative discovery gate. This deliberately skips higher-scoring Reserve entries whose specific switching advantage remains too weak. “Validate” means compare real workflows and seek paid repeated use; it does not mean build ten products.')
add();add('| Priority | Product and payer | Score | Proposed USD/mo | Accounts for $5K MRR |')
add('|---:|---|---:|---:|---:|')
for i,x in enumerate(short,1):
 add(f'| {i} | [{x["id"]} — {x["name"]}](catalog-100.md#{x["id"].lower()}) | {x["final_score"]:g} | ${x["pricing"]["monthly_usd"]} | {x["accounts_to_5000_mrr"]} |')
for i,x in enumerate(short,1):
 value,scope,test=selected[x['id']]
 value=value.replace(' pay ', ' could pay ')
 add();add(f'### {i}. {x["id"]} — {x["name"]}')
 add();add(f'**Buyer:** {x["buyer"]} **Payment hypothesis:** {value}')
 add();add(f'**SaaS scope:** {scope}')
 add();add('**Competitive check:** '+' '.join(f'[{c["name"]}]({c["url"]}) — {c["facts"]}' for c in distinct_vendors(x['competitors'])))
 add();add(f'**Argument against building:** {x["review"]["reason"]}')
 add();add(f'**Decisive test:** {test}')
 add();add(f'**Delivery envelope:** {x["effort_weeks"][0]}–{x["effort_weeks"][1]} full-time builder-weeks; estimated pilot cash ${x["cost"]["pilot_usd_month"][0]}–{x["cost"]["pilot_usd_month"][1]}/month with stated quotas. These are unmeasured estimates, excluding acquisition, support labor and assurance work. **Stop:** {x["kill_gate"]}')
add();add('## Why apparently attractive products moved down')
add();add('- **Generic onboarding:** Rocketlane already covers customer portals and approvals, while [Dock](https://www.dock.us/pricing) also offers customer workspaces. S083 needs a specific repeated failure those tools leave unresolved.\n- **Grant administration:** [Grantseeker](https://grantseeker.io/pricing?lg_redirect=1) supplies a low-cost alternative; comparing only with Instrumentl would overstate room for a $129 product. S086 remains Reserve.\n- **Engineering escalation:** [Linear’s Zendesk integration](https://linear.app/docs/zendesk) already connects support and engineering work. S070 needs more than ticket synchronization.\n- **Paid newsletters and storefronts:** incumbent platforms already combine publishing, payments and customer access at accessible entry prices. No convincing switching reason emerged for S038/S044.\n- **Security enforcement, confidential investigations, regulated cases and billing:** some have strong pain and budget, but assurance, correctness, support and integration requirements defeat a first $20–50 pilot business. Higher revenue can fund reconsideration; $300 hosting alone cannot fund every obligation.')
add();add('## Paths to $5,000 MRR')
add();add('These are arithmetic scenarios, not forecasts. Prices are our hypotheses; there are no acquired customers. Counts assume full-price active subscriptions with no discounts or failed payments.')
add();add('| Portfolio scenario | Calculation | Gross MRR |\n|---|---:|---:|\n| One $149 product | 34 organizations × $149 | $5,066 |\n| Two $149 products | 18 + 18 organizations × $149 | $5,364 |\n| Three products at $149, $149 and $129 | 12 × $149 + 12 × $149 + 12 × $129 | $5,124 |\n| One $199 product | 26 organizations × $199 | $5,174 |\n| One $99 product | 51 organizations × $99 | $5,049 |')
add();add('MRR is not profit. Payment fees, refunds, acquisition, support, taxes and infrastructure reduce what remains. At an illustrative 3% monthly logo churn, 34 accounts require roughly one replacement customer each month merely to hold the account base; this is a stress scenario, not a churn benchmark. Lifetime and setup payments add cash but contribute no MRR.')
add();add('Launching 100 paid-hosted products at $20–50 each already implies $2,000–5,000 monthly infrastructure spending before labor or acquisition. The better path under this target is one complete workflow, repeated paid use, then a second product only when its distribution and support burden can be funded. Keep the 100-product catalog as options, not a simultaneous build queue.')
add();add('## Pricing and product boundaries')
add();add('| Model | Recommendation | Conditions |\n|---|---|---|\n| Monthly subscription | Default for shared operational records | Start with organization/workspace pricing, bounded active cases and storage; charge for recurring workflow completion. |\n| Annual subscription | Offer after repeated use is demonstrated | Show the full annual commitment; any discount must leave room for support and costs. |\n| Freemium | Selective, capped acquisition product | One sample workflow, small record quota or solo tier; measure support and activation. Free users alone are not validation. |\n| Lifetime | Finite/offline capabilities only initially | Templates, local utilities or bounded prepaid usage; never assume a one-time payment funds unlimited hosted collaboration. |\n| Setup/migration fee | Separate where real onboarding work exists | Charge and measure services separately; do not count service revenue as subscription MRR. |\n| AI/paid APIs | Optional metered add-on after revenue | Keep deterministic core workflows usable; observe unit cost before allowing usage above the initial budget. |')
add();add('A lower price is not a durable entry strategy by itself. The initial claim must be a workflow outcome the buyer cannot achieve economically with its existing tools. Price testing should compare that outcome and support burden, not merely undercut a published incumbent package.')
add();add('## Budget interpretation')
add();add(f'{checks["bootstrap_cash_fit"]} candidates have a stated pilot cash envelope at or below $50/month. That count means **an engineering hypothesis for capped test usage**, not verified production feasibility. The other {100-checks["bootstrap_cash_fit"]} exceed the envelope before considering excluded costs. Individual dossiers define users/organizations, records, files, communication or execution boundaries; root operations candidates now have explicit aggregate quotas.')
add();add('At $20–50, assume simple structured records, tightly bounded attachments and transactional email, customer-owned heavy compute, and no expensive data licenses or always-on AI. After paid usage, up to approximately $300 can fund measured database, backup, observability and integration growth. Independent security review, specialist legal work, custom migration and substantial human support are separate costs. A product requiring those before its first customer remains gated even if its database bill is small.')
add();add('Global means remotely distributable software, not immediate legal or commercial readiness in every country. Begin with an English-language, clearly defined buyer segment. Entity/payment-provider eligibility, tax treatment, contractual data handling, residency requirements and localization need a separate launch check for the chosen product and selling entity; this research does not establish those arrangements.')
add();add('## Three analysis iterations and uncertainty')
add();add(f'1. **Product and evidence qualification:** four lanes generated 25 candidates each. Every final record has an identifiable buyer, a persistent record, at least three workflow stages, roles, a price hypothesis, a channel test and a kill gate. {checks["official_source_urls"]} distinct official source URLs were opened across candidate research and review. Numeric prices keep billing, currency or selector uncertainty explicit.\n2. **Independent challenge:** a researcher other than the author challenged every record. Five overlapping concepts were replaced and reviewed; incomplete value loops and weak pilot quotas were corrected. Penalized risks and rejected wedges remain in the dataset.\n3. **Shortlist and sensitivity:** the 10 finalists each have at least two competitor vendors represented. Alternate weights emphasize acquisition or delivery feasibility. Qualitative gates override a high numerical score; a high Reserve score is not a hidden build recommendation.')
add();add('| Candidate | Base-weighted rank | Acquisition-heavy rank | Feasibility-heavy rank |')
add('|---|---:|---:|---:|')
for id in ['S052','S094','S055','S080','S039','S009','S013']:
 x=by[id];add(f'| {id} — {x["name"]} | {x["rank"]} | {x["sensitivity_ranks"]["distribution_first"]} | {x["sensitivity_ranks"]["feasibility_first"]} |')
add();add('The ranking is ordinal judgment. Differences of a few points should be treated as the same broad tier. Reviewer penalties are not statistically calibrated and some risks overlap the base dimensions; this is a limitation of the screening, not quantified confidence. The strongest directional result is migration delivery remaining first under both alternate priorities. BPO and localization drop when acquisition or feasibility receives more weight, so they should not displace an accessible candidate solely on workflow appeal.')
add();add('We verified competitor offers and observed pricing, not category market size, competitor revenue, buyer search volume, our conversion, CAC, retention or an underserved market. No TAM or success probability is invented. Existing-source accuracy is bounded by the opened pages; quote-based and conflicting dynamic prices remain unconfirmed. All channels are hypotheses until buyers are actually reached.')
add();add('## First validation cycle')
add();add('1. **Confirm buyer access.** Start with migration consultancies unless finance/accounting access is materially stronger. Build a list of qualified budget owners using authorized public or existing contacts; any outreach is a separate execution step.\n2. **Observe ten qualified buyers.** Ask for the last completed workflow, the cost of its failures and the current tools. Count organizations with an actual repeat process, not developers expressing interest.\n3. **Replay five customer artifacts.** Use redacted or permissioned data. Reproduce the workflow in both the current incumbent and a lightweight proposed flow; demonstrate where the latter removes work. Avoid importing live sensitive datasets before appropriate controls exist.\n4. **Seek three paid pilots.** Present a concrete $149/month offer and full manual/software boundaries. A letter of intent is weaker than payment, and a paid concierge service is not automatically SaaS MRR.\n5. **Require repeated use.** The buyer and external participant should complete another cycle without the founder doing the core work. Record support time, active usage, renewal/payment and correctness.\n6. **Choose one build.** Proceed only if the same product solves all three pilots without bespoke processing. Stop or revise when the listed kill gate appears. The numerical targets here are internal decision rules, not industry benchmarks.')
add();add('## Completed scope and pending decisions')
add();add('- Completed: fresh 100-product research, official category/pricing evidence, economics, independent challenge, scoring sensitivity and a ten-product shortlist.\n- Completed: all research outputs saved locally; previous product prototypes and runtime state were not changed.\n- Pending: founder buyer access, actual paid-demand evidence, measured operating costs, legal/payment launch details for the selected product and the decision to build.\n- Separate earlier objective: this turn completes a fresh 100-product exercise; it does not claim the earlier requested 1,000-to-100 funnel was completed.')
(ROOT/'decision-report.md').write_text('\n'.join(L)+'\n')
(ROOT/'shortlist-10.json').write_text(json.dumps([{'id':x['id'],'name':x['name'],'overall_rank':x['rank'],'score':x['final_score'],'proposed_monthly_usd':x['pricing']['monthly_usd'],'accounts_to_5000_mrr':x['accounts_to_5000_mrr']} for x in short],indent=2)+'\n')
print('Wrote decision report and ten-product shortlist')
